name: Build Gradle project

on:
  push:

jobs:
  build-gradle-project:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout project sources
      uses: actions/checkout@v6

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v3

    - name: Run build with Gradle Wrapper
      run: ./gradlew build

    - uses: actions/upload-artifact@v6
      with:
        name: animate.jar
        path: build/libs/animate.jar
